/* mprint returns the text generated by the output 
while mlogic traces the flow of the exection in this case put as '1','2','3','4','5'*/
options symbolgen mprint mlogic;
/*create a macro variable create*/
%macro create(put);
/*use do loop to return the values of i from the put and by to define the sequence*/
   %do i=1 %to &put %by 1 ;
      data _NULL_;
        %put &i;
      run;
   %end;
%mend create;
%create(5)
options nosymbolgen nomprint nomlogic;

